modLoader="javafml"
loaderVersion="[55,)"
license="MIT"
issueTrackerURL="https://github.com/Volwert123/more-food-forge/issues"

[[mods]]
    modId="more_food"
    version="${version}"
    displayName="More Food"
    updateJSONURL="https://api.modrinth.com/updates/kReQ7M8K/forge_updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-food-xd"
    logoFile="assets/more_food/icon.png"
    authors="Volwert123, moritz_htk"
    description='''This mod adds more food to Minecraft.'''

[[dependencies.more_food]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_food]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,)"
    ordering="NONE"
    side="BOTH"

[modproperties.more_food]
    catalogueItemIcon="more_food:cooked_carrot"